import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { redirect } from 'next/navigation';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'S N V S KOMAL | Portfolio',
  description: 'Generated by SNVS KOMAL',
  icons: {
    icon: '/icon-snvs.png',
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  if (typeof window !== "undefined" && window.location.pathname !== "/") {
    redirect("/");
  }

  return (
    <html lang="en">
      <head>
        <link rel="apple-touch-icon" href="/icon-snvs.png" />
        <link rel="icon" href="/icon-snvs.png" sizes="any" />
  
        </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}